CREATE DATABASE IF NOT EXISTS ktc_plan;

ALTER DATABASE ktc_plan CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

USE ktc_plan;

DROP TABLE IF EXISTS Plan;

CREATE TABLE Plan (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    writer_name VARCHAR(50) NOT NULL,
    pwd VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL
);

ALTER TABLE plan ADD COLUMN member_id BIGINT;
ALTER TABLE plan DROP COLUMN writer_name;
ALTER TABLE plan ADD CONSTRAINT fk_plan_member FOREIGN KEY (member_id) REFERENCES member(id);


ALTER TABLE Plan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE member CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;